import Head from 'next/head';
import styles from './hawaii.module.css';
import BackArrow from "./images/arrow.svg";

export default function Hawaii() {
  return (
    <>
      <Head>
        <title>'Apakau ka lā | Hawaii</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.2/dist/leaflet.css"
          integrity="sha256-sA+zWATbFveLLNqWO2gtiw3HL/lh1giY/Inf1BJ0z14="
          crossorigin="" />
      </Head>
      <a href="..">
        <BackArrow className="backArrow" />
      </a>
      <h1 className={styles.title}>How does the internet reach Hawaii   </h1>
      <h3>Hawaii Inter-Island Cable System</h3>
       <div id="map"></div>
      <p><b>Landing points:</b></p>
      <ul>
        <li>Lihue Terminal, Wailua Point, Kauai</li>
        <li>Ko Olina Terminal, Kahe Point, Oahu</li>
        <li>Koko Head Terminal, Sandy Beach, Oahu</li>
        <li>Kihei Terminal, Mokapu, Maui</li>
        <li>Kawaihae Terminal, Spencer Beach, Island of Hawaii</li>
      </ul>
      <script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js"
     integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg="
     crossorigin=""></script>
    </>
  );
}
