import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image';
import sun from './Sun.svg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>'Apakau ka lā</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <h1 className={styles.title}>
            'Apakau ka lā
          </h1>
          <p className={styles.description}>
            spreading the sun's rays <br/>
            <strong>broadband education for all</strong>
          </p>
          <Image className={styles.sun}
            src={sun}
            width="300em"
            height="200em"
          />
        </div>
        <div className={styles.grid}>

          <a href="internet" className={styles.card}>
            <h2>How the Internet Works &rarr;</h2>
            <p>Learn about the mechanisms of the Internet, including broadband, the World Wide Web, and more.</p>
          </a>

          <a href="hawaii" className={styles.card}>
            <h2>How the Internet Reaches Hawai'i &rarr;</h2>
            <p>Hawai'i is in the middle of the Pacific. Click here to learn how the Internet reaches us all the way out here!</p>
          </a>

          <a
            href="access   "
            className={styles.card}
          >
            <h2>How to access the Internet &rarr;</h2>
            <p>You made it to this webpage. Why don't you learn  how to take your Internet access to the next level?</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <b>A project by the SouthShoreCoders for HACC</b>
        </a>
      </footer>
    </div>
  )
}
